### ISSUE TITLE
Add ability to ignore occurrences to avoid flood

### ISSUE THREAD

**Issue by F36** [KristobalJunta/rss-to-telegram#2]
Traceback (most recent call last):
  File "main.py", line 56, in <module>
    bot.send_message(config.get('channel-id'), post.get('text'))
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/telebot/__init__.py", line 640, in send_message
    apihelper.send_message(self.token, chat_id, text, disable_web_page_preview, reply_to_message_id,
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/telebot/apihelper.py", line 201, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/telebot/apihelper.py", line 108, in _make_request
    json_result = _check_result(method_name, result)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/telebot/apihelper.py", line 135, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 429 Description: Too Many Requests: retry after 38

**Comment by KristobalJunta** [comment]
There is indeed no backoff implemented currently. Will try to add that. But also feel free to send a PR if you have a solution for that.

**Comment by craziks-creator** [comment]
![IMG_20201229_115530](https://user-images.githubusercontent.com/67502395/103263063-cad45080-49cc-11eb-8171-0d986f3e45aa.jpg)
