### ISSUE TITLE
Error line 46 in main.py

### ISSUE THREAD

**Issue by The-Mer0vingian** [KristobalJunta/rss-to-telegram#3]
Hello, ive got 2 issue when I try to start main.py

> python main.py

Traceback (most recent call last):
  File "main.py", line 46, in <module>
    post['date'] = get_timestamp(entry['published'])
  File "C:\Python38\lib\site-packages\feedparser\util.py", line 113, in __getitem__
    return dict.__getitem__

I dont understand why i got this.. Someone can explain me how to fix it?

**Comment by KristobalJunta** [comment]
@The-Mer0vingian not sure about it either.. could you please share more context on how you're using it - a code snippet maybe and versions of libs used.
